---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.4.2
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
from scipy import *
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation
import Methods.Deposition as DM
import Methods.PDESolver as PM
import Methods.Plotting as PL
import profile

# %matplotlib notebook

# #%load_ext Cython
```

This figure shows the evolution of plankton density and a chemical, as the plankton performs autochemotaxis. We simulate the following PDE system:

$$ \rho_{tt} + \rho_{t} = \rho_{xx} - \frac{\partial}{\partial x} \left[ \frac{c_x}{\sqrt{c_x^2 + \delta^2}} \rho \right]$$
$$c_t = d_1 c_{xx} - d_2 c + f(c) \rho$$

where $\rho(x,t)$ is the plankton density, $c(x,t)$ is the chemical concentration, $\delta$ is a run-and-tumble parameter, $d_1$ is the diffusion of the chemical, $d_2$ is the diffusion of the chemical, and $f(c)$ is the deposition function i.e. how much chemical the plankton produce. 

To simulate this, we utilize a Crank-Nicolson method on all terms except the autochemotaxis term, where we use an explicit Forward Euler. 

We show the evolution differences between the three different deposition functions: a constant deposition function (Fig. 6a), a switch (6b), and a linear switch (6c). 

This figure also comes with supplemental videos to show the evolution over time. 


## Figure 6a

This shows the evolution of our system where $f(c) = \gamma$, the constant deposition function. We overlay $c$ and $\rho$ on the same plot to show how they match each other. 

```{python}
Swimmers = PM.PlankChem(depFcn=DM.constantDep,left=0,right=5,d1=.2,d2=4,N=301,
                        dt=0.004,depMaxStr=0.01, depThreshold=0.25, depTransWidth=0.1, delta = 0.015)

NonDTime = 200 #The total non-dimensional time the simulation will run for
TotalTime = int(NonDTime/Swimmers.dt) #Total number of timesteps for the experiment
c0 = .2 #Initial Constant Value of Chemical for the experiment
Swimmers.CheckStability(c0) #checks the stability of the system. Do not comment out#
```

```{python}
##################################################
# This code runs the 1D coupled system of equations #                     
# with c as the chemical, which diffuses and decays #
# throughout the system, and which p, the total plankton #
# performs autochemotaxis in regards to this chemical. #

# CAC - TotalTime x N+1 array for evolution of the chemical #
# PAC - TotalTime x N+1 array for evolution of the plankton #
# CTC - TotalTime x 1 array for total amount of chemical in the system #
# PTC - TotalTime x 1 array for total plankton in the system #
#################################################


#set up chemical, plankton, and totals
CAC, PAC, CTC, PTC = Swimmers.initial_conditionsSO(const=c0, steps=TotalTime)

#perturb the initial solution
CAC[1,:], PAC[1,:], CTC[1], PTC[1] = Swimmers.firstStepSO(CAC[0,:],PAC[0,:])

#Complete the iterations necessary
for i in range(1, len(CTC)-1):
    CAC[i+1,:], PAC[i+1,:], CTC[i+1], PTC[i+1] = Swimmers.SecondOrder(CAC[i,:],PAC[i,:],PAC[i-1,:])
```

```{python}
fig, axs = plt.subplots(nrows=1, ncols=5,figsize=(25,5),tight_layout=True,sharey='row')

lns1 = axs[0].plot(Swimmers.xm,PAC[0],color='r',label='Plankton',linewidth=2.5)
axs[0].ticklabel_format(style='sci', scilimits=(2,2),axis='y',useMathText=True)
axs[0].yaxis.get_offset_text().set_fontsize(16)
ax2 = axs[0].twinx()  #create a second axes that shares the same x-axis
lns2 = ax2.plot(Swimmers.xm,CAC[0],color='b',linestyle='--',label='Chemical',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y')
ax2.set_yticklabels([])
ax2.locator_params(nbins=3,axis='y')
ax2.set_ylim(0e-1,5e-1)
lns = lns1+lns2
labs = [l.get_label() for l in lns]
axs[0].legend(lns, labs, loc=0, prop={"size":19})


axs[0].ticklabel_format(style='plain',axis='x')
axs[0].set_xlim(0,Swimmers.right)
axs[0].set_ylim(0,max(PAC[-1])+10)
axs[0].set_xlabel(r'$x$',fontsize=30)
axs[0].set_ylabel(r'Plankton Density', fontsize=22, color='r')
axs[0].set_title(r'$t = {0}$',fontsize=30)
axs[0].locator_params(nbins=5,axis='x')
axs[0].locator_params(nbins=3,axis='y')

axs[0].tick_params(labelsize=18)

k = int(4/Swimmers.dt)
axs[1].plot(Swimmers.xm,PAC[k],color='r',linewidth=2.5)
axs[1].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[1].ticklabel_format(style='plain',axis='x')
axs[1].set_xlim(0,Swimmers.right)
axs[1].set_xlabel(r'$x$',fontsize=30)
axs[1].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[1].locator_params(nbins=3,axis='y')
axs[1].tick_params(labelsize=18)

ax2 = axs[1].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAC[k],color='b',linestyle='--',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y')
ax2.set_yticklabels([])
ax2.set_ylim(0e-1,5e-1)

ax2.locator_params(nbins=3,axis='y')





k = int(20/Swimmers.dt)
axs[2].plot(Swimmers.xm,PAC[k],color='r',linewidth=2.5)
axs[2].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[2].ticklabel_format(style='plain',axis='x')
axs[2].set_xlim(0,Swimmers.right)
axs[2].set_xlabel(r'$x$',fontsize=30)
axs[2].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[2].locator_params(nbins=3,axis='y')
axs[2].tick_params(labelsize=18)
axs[2].yaxis.get_offset_text().set_fontsize(15)
ax2 = axs[2].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAC[k],color='b',linestyle='--',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y')
ax2.set_yticklabels([])
ax2.set_ylim(0e-1,5e-1)

ax2.locator_params(nbins=3,axis='y')


k = int(100/Swimmers.dt)
axs[3].plot(Swimmers.xm,PAC[k],color='r',linewidth=2.5)
axs[3].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[3].ticklabel_format(style='plain',axis='x')
axs[3].set_xlim(0,Swimmers.right)
axs[3].set_xlabel(r'$x$',fontsize=30)
axs[3].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[3].locator_params(nbins=3,axis='y')
axs[3].tick_params(labelsize=18)
axs[3].yaxis.get_offset_text().set_fontsize(15)
ax2 = axs[3].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAC[k],color='b',linestyle='--',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y')
ax2.set_yticklabels([])
ax2.set_ylim(0e-1,5e-1)

ax2.locator_params(nbins=3,axis='y')


k = int(150/Swimmers.dt)
axs[4].plot(Swimmers.xm,PAC[k],color='r',linewidth=2.5)
axs[4].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[4].ticklabel_format(style='plain',axis='x')
axs[4].set_xlim(0,Swimmers.right)
axs[4].set_xlabel(r'$x$',fontsize=30)
axs[4].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[4].locator_params(nbins=3,axis='y')
axs[4].tick_params(labelsize=18)
ax2 = axs[4].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAC[k],color='b',linestyle='--',linewidth=2.5)
ax2.yaxis.get_offset_text().set_fontsize(16)

#ax2.ticklabel_format(style='sci', scilimits=(-2,-2),axis='y')
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y',useMathText=True)
ax2.set_ylabel(r'Chemical Concentration', color='blue',fontsize=22,rotation=-90,labelpad=30)
ax2.tick_params(labelsize=18)
ax2.set_ylim(0e-1,5e-1)
ax2.locator_params(nbins=4,axis='y')

plt.savefig('../Final_Figures/Figure_6a')
```

```{python}
np.save('./Data/Figure_6a_Plankton.npy',PAC)
np.save('./Data/Figure_6a_Chemical.npy',CAC)
```

### Supplemental Video for Figure 6a

```{python}
# %matplotlib notebook

fig2, ax1 = plt.subplots()
time = 0

line, = ax1.plot(Swimmers.xm,PAC[time,:], color='red',linestyle = '-', linewidth = 2, label='Plankton')
ax1.set_xlabel(r'$x$',fontsize=20)
ax1.set_ylabel(r'Plankton', color='red',fontsize=20)
ax1.set_xlim(Swimmers.left, Swimmers.right)

ax2 = ax1.twinx()  #create a second axes that shares the same x-axis
line2, = ax2.plot(Swimmers.xm, CAC[time,:], color='blue', linestyle = '--', linewidth = 2, label='Chemical')
ax2.set_ylabel(r'Chemical Concentration', color='blue',fontsize=20)
ax2.set_xlim(Swimmers.left, Swimmers.right)
fig2.tight_layout()


plt.title(r'Plankton/Chemical, Time = {0}, $f(c) = f_1(c)$'.format(0))

#lns = line, + line2,
#labs = [l.get_label() for l in lns]
#axs[0].legend(lns, labs, loc=0, prop={"size":19})

ax1.legend(loc=2)
ax2.legend(loc=1)
ax1.set_ylim(0,max(PAC[-1])+10)
ax2.set_ylim(0e-1,5e-1)
ax1.tick_params(labelsize=15)
ax2.tick_params(labelsize=15)
ax1.ticklabel_format(style='sci', scilimits=(2,2),axis='y',useMathText=True)
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y',useMathText=True)


def init():  # only required for blitting to give a clean slate.
    line.set_ydata([np.nan] * len(Swimmers.xm))
    line2.set_ydata([np.nan] * len(Swimmers.xm))
    return line,line2,


def animate(i):
    line.set_ydata(PAC[i,:])  # update the data.
    line2.set_ydata(CAC[i,:])  # update the data

    plt.title(r'Simulation Time = {0}, $f(c) = f_1(c)$'.format(round(i*Swimmers.dt,3)))
    return line, line2,


ani = matplotlib.animation.FuncAnimation(fig2, animate, init_func=init, frames=range(0,int(160/Swimmers.dt),3), interval=1, blit=True,repeat=False)
ani.save('../Final_Figures/Figure_6a_Supplemental_Video.mp4', writer='ffmpeg')
```

## Figure 6b

This shows the evolution of our system where $f(c) = f_2(c)$ is the switch deposition function (see Figure 3). We overlay $c$ and $\rho$ on the same plot to show how they match each other. 

```{python}
Swimmers = PM.PlankChem(depFcn=DM.atanDep,left=0,right=5,d1=.2,d2=4,N=301,
                        dt=0.004,depMaxStr=0.01, depThreshold=0.25, depTransWidth=0.04, delta = 0.015)

NonDTime = 400 #The total non-dimensional time the simulation will run for
TotalTime = int(NonDTime/Swimmers.dt) #Total number of timesteps for the experiment
c0 = .2 #Initial Constant Value of Chemical for the experiment
Swimmers.CheckStability(c0) #checks the stability of the system. Do not comment out#
```

```{python}
##################################################
# This code runs the 1D coupled system of equations #                     
# with c as the chemical, which diffuses and decays #
# throughout the system, and which p, the total plankton #
# performs autochemotaxis in regards to this chemical. #

# CAS - TotalTime x N+1 array for evolution of the chemical #
# PAS - TotalTime x N+1 array for evolution of the plankton #
# CTS - TotalTime x 1 array for total amount of chemical in the system #
# PTS - TotalTime x 1 array for total plankton in the system #
#################################################


#set up chemical, plankton, and totals
CAS, PAS, CTS, PTS = Swimmers.initial_conditionsSO(const=c0, steps=TotalTime)

#perturb the initial solution
CAS[1,:], PAS[1,:], CTS[1], PTS[1] = Swimmers.firstStepSO(CAS[0,:],PAS[0,:])

#Complete the iterations necessary
for i in range(1, len(CTS)-1):
    CAS[i+1,:], PAS[i+1,:], CTS[i+1], PTS[i+1] = Swimmers.SecondOrder(CAS[i,:],PAS[i,:],PAS[i-1,:])
```

```{python}
fig, axs = plt.subplots(nrows=1, ncols=5,figsize=(25,5),tight_layout=True,sharey='row')

lns1 = axs[0].plot(Swimmers.xm,PAS[0],color='r',label='Plankton',linewidth=2.5)
axs[0].ticklabel_format(style='sci', scilimits=(2,2),axis='y',useMathText=True)
axs[0].yaxis.get_offset_text().set_fontsize(16)
ax2 = axs[0].twinx()  #create a second axes that shares the same x-axis
lns2 = ax2.plot(Swimmers.xm,CAS[0],color='b',linestyle='--',label='Chemical',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y')
ax2.set_yticklabels([])
ax2.locator_params(nbins=3,axis='y')
ax2.set_ylim(0e-1,3e-1)
lns = lns1+lns2
labs = [l.get_label() for l in lns]
axs[0].legend(lns, labs, loc=0, prop={"size":19})


axs[0].ticklabel_format(style='plain',axis='x')
axs[0].set_xlim(0,Swimmers.right)
axs[0].set_ylim(0,max(PAS[-1])+10)
axs[0].set_xlabel(r'$x$',fontsize=30)
axs[0].set_ylabel(r'Plankton Density', fontsize=22, color='r')
axs[0].set_title(r'$t = {0}$',fontsize=30)
axs[0].locator_params(nbins=5,axis='x')
axs[0].locator_params(nbins=4,axis='y')

axs[0].tick_params(labelsize=18)

k = int(4/Swimmers.dt)
axs[1].plot(Swimmers.xm,PAS[k],color='r',linewidth=2.5)
axs[1].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[1].ticklabel_format(style='plain',axis='x')
axs[1].set_xlim(0,Swimmers.right)
axs[1].set_xlabel(r'$x$',fontsize=30)
axs[1].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[1].locator_params(nbins=5,axis='x')
axs[1].tick_params(labelsize=18)

ax2 = axs[1].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAS[k],color='b',linestyle='--',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y')
ax2.set_yticklabels([])
ax2.set_ylim(0e-1,3e-1)
ax2.locator_params(nbins=3,axis='y')





k = int(20/Swimmers.dt)
axs[2].plot(Swimmers.xm,PAS[k],color='r',linewidth=2.5)
axs[2].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[2].ticklabel_format(style='plain',axis='x')
axs[2].set_xlim(0,Swimmers.right)
axs[2].set_xlabel(r'$x$',fontsize=30)
axs[2].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[2].locator_params(nbins=4)
axs[2].tick_params(labelsize=18)
axs[2].yaxis.get_offset_text().set_fontsize(15)
ax2 = axs[2].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAS[k],color='b',linestyle='--',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y')
ax2.set_yticklabels([])
ax2.set_ylim(0e-1,3e-1)

ax2.locator_params(nbins=5,axis='x')
ax2.locator_params(nbins=3,axis='y')

k = int(300/Swimmers.dt)
axs[3].plot(Swimmers.xm,PAS[k],color='r',linewidth=2.5)
axs[3].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[3].ticklabel_format(style='plain',axis='x')
axs[3].set_xlim(0,Swimmers.right)
axs[3].set_xlabel(r'$x$',fontsize=30)
axs[3].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[3].locator_params(nbins=4)
axs[3].tick_params(labelsize=18)
axs[3].yaxis.get_offset_text().set_fontsize(15)
ax2 = axs[3].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAS[k],color='b',linestyle='--',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y')
ax2.set_yticklabels([])
ax2.set_ylim(0e-1,3e-1)
ax2.locator_params(nbins=5,axis='x')
ax2.locator_params(nbins=3,axis='y')


k = int(350/Swimmers.dt)
axs[4].plot(Swimmers.xm,PAS[k],color='r',linewidth=2.5)
axs[4].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[4].ticklabel_format(style='plain',axis='x')
axs[4].set_xlim(0,Swimmers.right)
axs[4].set_xlabel(r'$x$',fontsize=30)
axs[4].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[4].locator_params(nbins=4)
axs[4].tick_params(labelsize=18)
ax2 = axs[4].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAS[k],color='b',linestyle='--',linewidth=2.5)
ax2.locator_params(nbins=5,axis='x')

ax2.yaxis.get_offset_text().set_fontsize(16)

#ax2.ticklabel_format(style='sci', scilimits=(-2,-2),axis='y')
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y',useMathText=True)
ax2.set_ylabel(r'Chemical Concentration', color='blue',fontsize=22,rotation=-90,labelpad=30)
ax2.tick_params(labelsize=18)
ax2.set_ylim(0e-1,3e-1)
ax2.locator_params(nbins=4,axis='y')

#plt.savefig('../Final_Figures/Figure_6b')
```

```{python}
np.save('./Data/Figure_6b_Plankton.npy',PAS)
np.save('./Data/Figure_6b_Chemical.npy',CAS)
```

### Supplemental Video for Figure 6b

```{python}
fig2, ax1 = plt.subplots()
time = 0

line, = ax1.plot(Swimmers.xm,PAS[time,:], color='red',linestyle = '-', linewidth = 2, label='Plankton')
ax1.set_xlabel(r'$x$',fontsize=20)
ax1.set_ylabel(r'Plankton', color='red',fontsize=20)
ax1.set_xlim(Swimmers.left, Swimmers.right)

ax2 = ax1.twinx()  #create a second axes that shares the same x-axis
line2, = ax2.plot(Swimmers.xm, CAS[time,:], color='blue', linestyle = '--', linewidth = 2, label='Chemical')
ax2.set_ylabel(r'Chemical Concentration', color='blue',fontsize=20)
ax2.set_xlim(Swimmers.left, Swimmers.right)
fig2.tight_layout()

plt.title(r'Plankton/Chemical, Time = {0}, $f(c) = f_1(c)$'.format(0))

ax1.legend(loc=2)
ax2.legend(loc=4)
ax1.set_ylim(0,max(PAS[-1])+10)
ax2.set_ylim(0e-1,3e-1)
ax1.tick_params(labelsize=15)
ax2.tick_params(labelsize=15)

def init():  # only required for blitting to give a clean slate.
    line.set_ydata([np.nan] * len(Swimmers.xm))
    line2.set_ydata([np.nan] * len(Swimmers.xm))
    return line,line2,


def animate(i):
    line.set_ydata(PAS[i,:])  # update the data.
    line2.set_ydata(CAS[i,:])  # update the data

    plt.title(r'Plankton/Chemical, Time = {0}, $f(c) = f_2(c)$'.format(round(i*Swimmers.dt,3)))
    return line, line2,


ani = matplotlib.animation.FuncAnimation(fig2, animate, init_func=init, frames=range(0,int(len(PAS)),30), interval=1, blit=True,repeat=False)
#ani.save('../Final_Figures/Figure_6b_Supplemental_Video.mp4', writer='ffmpeg')
```

## Figure 6c

This shows the evolution of our system where $f(c) = f_3(c)$ is the linear switch deposition function (see Figure 3). We overlay $c$ and $\rho$ on the same plot to show how they match each other. 

```{python}
Swimmers = PM.PlankChem(depFcn=DM.linAtanDep,left=0,right=5,d1=.2,d2=4,N=301,
                        dt=0.004,depMaxStr=0.01, depThreshold=0.25, depTransWidth=0.04, delta = 0.015)


NonDTime = 150 #The total non-dimensional time the simulation will run for
TotalTime = int(NonDTime/Swimmers.dt) #Total number of timesteps for the experiment
c0 = .2 #Initial Constant Value of Chemical for the experiment
Swimmers.CheckStability(c0) #checks the stability of the system. Do not comment out#
```

```{python}
##################################################
# This code runs the 1D coupled system of equations #                     
# with c as the chemical, which diffuses and decays #
# throughout the system, and which p, the total plankton #
# performs autochemotaxis in regards to this chemical. #

# CAL - TotalTime x N+1 array for evolution of the chemical #
# PAL - TotalTime x N+1 array for evolution of the plankton #
# CTL - TotalTime x 1 array for total amount of chemical in the system #
# PTL - TotalTime x 1 array for total plankton in the system #
#################################################


#set up chemical, plankton, and totals
CAL, PAL, CTL, PTL = Swimmers.initial_conditionsSO(const=c0, steps=TotalTime)

#perturb the initial solution
CAL[1,:], PAL[1,:], CTL[1], PTL[1] = Swimmers.firstStepSO(CAL[0,:],PAL[0,:])

#Complete the iterations necessary
for i in range(1, len(CTL)-1):
    CAL[i+1,:], PAL[i+1,:], CTL[i+1], PTL[i+1] = Swimmers.SecondOrder(CAL[i,:],PAL[i,:],PAL[i-1,:])
```

```{python}
fig, axs = plt.subplots(nrows=1, ncols=5,figsize=(25,5),tight_layout=True,sharey='row')

lns1 = axs[0].plot(Swimmers.xm,PAL[0],color='r',label='Plankton',linewidth=2.5)
axs[0].ticklabel_format(style='sci', scilimits=(2,2),axis='y',useMathText=True)
axs[0].yaxis.get_offset_text().set_fontsize(16)
ax2 = axs[0].twinx()  #create a second axes that shares the same x-axis
lns2 = ax2.plot(Swimmers.xm,CAL[0],color='b',linestyle='--',label='Chemical',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-2,-2),axis='y')
ax2.set_yticklabels([])
ax2.locator_params(nbins=4,axis='y')
ax2.set_ylim(0e-1,3e-1)
lns = lns1+lns2
labs = [l.get_label() for l in lns]
ax2.locator_params(nbins=5,axis='x')
axs[0].legend(lns, labs, loc=0, prop={"size":19})


axs[0].ticklabel_format(style='plain',axis='x')
axs[0].set_xlim(0,Swimmers.right)
axs[0].set_ylim(0,max(PAL[-1])+10)
axs[0].set_xlabel(r'$x$',fontsize=30)
axs[0].set_ylabel(r'Plankton Density', fontsize=22, color='r')
axs[0].set_title(r'$t = {0}$',fontsize=30)
axs[0].locator_params(nbins=5,axis='x')
axs[0].locator_params(nbins=4,axis='y')

axs[0].tick_params(labelsize=18)

k = int(4/Swimmers.dt)
axs[1].plot(Swimmers.xm,PAL[k],color='r',linewidth=2.5)
axs[1].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[1].ticklabel_format(style='plain',axis='x')
axs[1].set_xlim(0,Swimmers.right)
axs[1].set_xlabel(r'$x$',fontsize=30)
axs[1].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[1].locator_params(nbins=4)
axs[1].tick_params(labelsize=18)

ax2 = axs[1].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAL[k],color='b',linestyle='--',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(2,2),axis='y')
ax2.set_yticklabels([])
ax2.set_ylim(0e-1,3e-1)
ax2.locator_params(nbins=5,axis='x')
ax2.locator_params(nbins=3,axis='y')





k = int(20/Swimmers.dt)
axs[2].plot(Swimmers.xm,PAL[k],color='r',linewidth=2.5)
axs[2].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[2].ticklabel_format(style='plain',axis='x')
axs[2].set_xlim(0,Swimmers.right)
axs[2].set_xlabel(r'$x$',fontsize=30)
axs[2].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[2].locator_params(nbins=4)
axs[2].tick_params(labelsize=18)
axs[2].yaxis.get_offset_text().set_fontsize(15)
ax2 = axs[2].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAL[k],color='b',linestyle='--',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-2,-2),axis='y')
ax2.set_yticklabels([])
ax2.set_ylim(0e-1,3e-1)
ax2.locator_params(nbins=5,axis='x')
ax2.locator_params(nbins=3,axis='y')


k = int(75/Swimmers.dt)
axs[3].plot(Swimmers.xm,PAL[k],color='r',linewidth=2.5)
axs[3].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[3].ticklabel_format(style='plain',axis='x')
axs[3].set_xlim(0,Swimmers.right)
axs[3].set_xlabel(r'$x$',fontsize=30)
axs[3].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[3].locator_params(nbins=5)
axs[3].tick_params(labelsize=18)
axs[3].yaxis.get_offset_text().set_fontsize(15)
ax2 = axs[3].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAL[k],color='b',linestyle='--',linewidth=2.5)
ax2.ticklabel_format(style='sci', scilimits=(-2,-2),axis='y')
ax2.set_yticklabels([])
ax2.set_ylim(0e-1,3e-1)
ax2.locator_params(nbins=5,axis='x')
ax2.locator_params(nbins=3,axis='y')


k = int(100/Swimmers.dt)
axs[4].plot(Swimmers.xm,PAL[k],color='r',linewidth=2.5)
axs[4].ticklabel_format(style='sci', scilimits=(2,2),axis='y')
axs[4].ticklabel_format(style='plain',axis='x')
axs[4].set_xlim(0,Swimmers.right)
axs[4].set_xlabel(r'$x$',fontsize=30)
axs[4].set_title(r'$t = {0}$'.format(round(Swimmers.dt*k)),fontsize=30)
axs[4].locator_params(nbins=4)
axs[4].tick_params(labelsize=18)
ax2 = axs[4].twinx()  #create a second axes that shares the same x-axis
ax2.plot(Swimmers.xm,CAL[k],color='b',linestyle='--',linewidth=2.5)
ax2.yaxis.get_offset_text().set_fontsize(16)

#ax2.ticklabel_format(style='sci', scilimits=(-2,-2),axis='y')
ax2.ticklabel_format(style='sci', scilimits=(-1,-1),axis='y',useMathText=True)
ax2.set_ylabel(r'Chemical Concentration', color='blue',fontsize=22,rotation=-90,labelpad=30)
ax2.tick_params(labelsize=18)
ax2.set_ylim(0e-1,3e-1)
ax2.locator_params(nbins=4,axis='y')
ax2.locator_params(nbins=5,axis='x')


plt.savefig('../Final_Figures/Figure_6c')
```

```{python}
np.save('./Data/Figure_6c_Plankton.npy',PAL[:int(len(PAL)/5)])
np.save('./Data/Figure_6c_Chemical.npy',CAL[:int(len(CAL)/5)])
```

```{python}
fig2, ax1 = plt.subplots()
time = 0

line, = ax1.plot(Swimmers.xm,PAL[time,:], color='red',linestyle = '-', linewidth = 2, label='Plankton')
ax1.set_xlabel(r'$x$',fontsize=20)
ax1.set_ylabel(r'Plankton', color='red',fontsize=20)
ax1.set_xlim(Swimmers.left, Swimmers.right)

ax2 = ax1.twinx()  #create a second axes that shares the same x-axis
line2, = ax2.plot(Swimmers.xm, CAL[time,:], color='blue', linestyle = '--', linewidth = 2, label='Chemical')
ax2.set_ylabel(r'Chemical Concentration', color='blue',fontsize=20)
ax2.set_xlim(Swimmers.left, Swimmers.right)
fig2.tight_layout()

plt.title(r'Plankton/Chemical, Time = {0}, $f(c) = f_1(c)$'.format(0))

ax1.legend(loc=2)
ax2.legend(loc=4)
ax1.set_ylim(0,max(PAL[-1])+10)
ax2.set_ylim(0e-1,3e-1)
ax1.tick_params(labelsize=15)
ax2.tick_params(labelsize=15)

def init():  # only required for blitting to give a clean slate.
    line.set_ydata([np.nan] * len(Swimmers.xm))
    line2.set_ydata([np.nan] * len(Swimmers.xm))
    return line,line2,


def animate(i):
    line.set_ydata(PAL[i,:])  # update the data.
    line2.set_ydata(CAL[i,:])  # update the data

    plt.title(r'Plankton/Chemical, Time = {0}, $f(c) = f_3(c)$'.format(round(i*Swimmers.dt,3)))
    return line, line2,


ani = matplotlib.animation.FuncAnimation(fig2, animate, init_func=init, frames=range(0,int(1000/Swimmers.dt),50), interval=1, blit=True,repeat=False)
#ani.save('../Final_Figures/Figure_6b_Supplemental_Video.mp4', writer='ffmpeg')
```

```{python}
A1 = np.load('./Data/Figure_6a_Chemical.npy')
A2 = np.load('./Data/Figure_6b_Chemical.npy')
A3 = np.load('./Data/Figure_6c_Chemical.npy')
```

```{python}
Sums1 = []
for j in range(len(A1)):
    Sums1.append(np.sum(A1[j]*(5/302)))
Sums1 = np.append(Sums1,Sums1[-1]+np.zeros(75000))
Sums2 = []
for j in range(len(A2)):
    Sums2.append(np.sum(A2[j]*(5/302)))
Sums3 = []
for j in range(len(A3)):
    Sums3.append(np.sum(A3[j]*(5/302)))
Sums3 = np.append(Sums3,Sums3[-1]+np.zeros(75000))
```

```{python}
fig, ax = plt.subplots(figsize=(7,5),tight_layout=True)

colors = ['#000000','#009E73','#D55E00'] 
times = np.linspace(0,400,int(125000))
ax.plot(times,Sums1,color=colors[0],linestyle = '--',linewidth=3,label=r'$f_1(c)$')
ax.plot(times,Sums2,color=colors[1],linestyle = '-',linewidth=3,label=r'$f_2(c)$')
ax.plot(times,Sums3,color=colors[2],linestyle = ':',linewidth=3,label=r'$f_3(c)$')
ax.legend(loc=0,fontsize=19)
ax.set_xlabel(r'Time, $t$',fontsize=20)
ax.set_ylabel(r'Total Chemical, $C(t)$',fontsize=20)
ax.set_title('Total Chemical Over Time',fontsize=20)
ax.tick_params(labelsize=18)
ax.locator_params(nbins=5,axis='x')
ax.locator_params(nbins=4,axis='y')
ax.ticklabel_format(style='plain',axis='x')
ax.set_xlim(0,350)
plt.savefig('../Final_Figures/Fig6d.png')
```

```{python}

```
